; PlatformIO Project Configuration File
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .

[env]
build_flags =
        '-Wall'
	'-Wno-deprecated'
lib_deps =
	symlink://../og3
	thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
	bblanchon/ArduinoJson@^7.0.0
	bakercp/CRC32@^2.0.0
	esphome/ESPAsyncWebServer-esphome@^3.0.0
	heman/AsyncMqttClient-esphome@^1.0.0
	esphome/ESPAsyncTCP-esphome@^2.0.0
lib_ldf_mode = deep+
check_tool = cppcheck
check_skip_packages = yes

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

[env:native]
platform = native
build_flags =
	${env.build_flags}
	'-D NATIVE'
